In [25]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [26]:
space_df = pd.read_csv("data/Space_Corrected.csv")
space_df.head()

,Unnamed: 0.1,Unnamed: 0,Company Name,Location,Datum,Detail,Status Rocket,Rocket,Status Mission
0,0,0,SpaceX,"LC-39A, Kennedy Space Center, Florida, USA","Fri Aug 07, 2020 05:12 UTC",Falcon 9 Block 5 | Starlink V1 L9 & BlackSky,StatusActive,50.0,Success
1,1,1,CASC,"Site 9401 (SLS-2), Jiuquan Satellite Launch Ce...","Thu Aug 06, 2020 04:01 UTC",Long March 2D | Gaofen-9 04 & Q-SAT,StatusActive,29.75,Success
2,2,2,SpaceX,"Pad A, Boca Chica, Texas, USA","Tue Aug 04, 2020 23:57 UTC",Starship Prototype | 150 Meter Hop,StatusActive,NaN,Success
3,3,3,Roscosmos,"Site 200/39, Baikonur Cosmodrome, Kazakhstan","Thu Jul 30, 2020 21:25 UTC",Proton-M/Briz-M | Ekspress-80 & Ekspress-103,StatusActive,65.0,Success
4,4,4,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA","Thu Jul 30, 2020 11:50 UTC",Atlas V 541 | Perseverance,StatusActive,145.0,Success

In [27]:
space1_df = pd.read_csv("data/Space_Launches.txt", index_col=False)
space1_df.head()

C:\Users\nmill\AppData\Local\Temp\ipykernel_26972\3046935228.py:1: ParserWarning: Length of header or names does not match length of data. This leads to a loss of data with index_col=False.
  space1_df = pd.read_csv("data/Space_Launches.txt", index_col=False)

,Company Name,Location,Datum,Detail,Status Rocket,Rocket,Status Mission
0,SpaceX,"SLC-4E, Vandenberg SFB, CA",Feb 25 2026 14:12 UTC,Starlink Group 17-26,Falcon 9 Block 5,StatusActive,52.0
1,SpaceX,"SLC-40, Cape Canaveral SFS, FL",Feb 24 2026 23:04 UTC,Starlink Group 6-110,Falcon 9 Block 5,StatusActive,52.0
2,SpaceX,"SLC-4E, Vandenberg SFB, CA",Feb 21 2026 13:42 UTC,Starlink Group 11-5,Falcon 9 Block 5,StatusActive,52.0
3,CASC,"Xichang Satellite Launch Center, China",Feb 21 2026 09:30 UTC,Geely-03 Group 01,Long March 2C,StatusActive,30.0
4,SpaceX,"SLC-40, Cape Canaveral SFS, FL",Feb 19 2026 10:48 UTC,Starlink Group 6-109,Falcon 9 Block 5,StatusActive,52.0

In [28]:
space_df.drop(['Unnamed: 0.1', 'Unnamed: 0'], axis=1, inplace=True)

In [29]:
space_df.head()

,Company Name,Location,Datum,Detail,Status Rocket,Rocket,Status Mission
0,SpaceX,"LC-39A, Kennedy Space Center, Florida, USA","Fri Aug 07, 2020 05:12 UTC",Falcon 9 Block 5 | Starlink V1 L9 & BlackSky,StatusActive,50.0,Success
1,CASC,"Site 9401 (SLS-2), Jiuquan Satellite Launch Ce...","Thu Aug 06, 2020 04:01 UTC",Long March 2D | Gaofen-9 04 & Q-SAT,StatusActive,29.75,Success
2,SpaceX,"Pad A, Boca Chica, Texas, USA","Tue Aug 04, 2020 23:57 UTC",Starship Prototype | 150 Meter Hop,StatusActive,NaN,Success
3,Roscosmos,"Site 200/39, Baikonur Cosmodrome, Kazakhstan","Thu Jul 30, 2020 21:25 UTC",Proton-M/Briz-M | Ekspress-80 & Ekspress-103,StatusActive,65.0,Success
4,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA","Thu Jul 30, 2020 11:50 UTC",Atlas V 541 | Perseverance,StatusActive,145.0,Success